#!/bin/sh

# Run lint checks & unit testing before the push

echo "Running Unit tests and Lint checks..."
./gradlew test lintRelease > /dev/null

STATUS=$?
if [ ${STATUS} -ne 0 ]; then
   echo "Error: Unit tests/Lint checks failed!! Run \"./gradlew test lintRelease\" for more details."
else
   echo "Completed!"
fi

exit ${STATUS}